on:
  push:
     branches:
       - main



name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","ggplot2","dplyr","tidyr","lubridate","remotes","memoise"))'
      - name: Install McMasterPandemic
        run: Rscript -e 'remotes::install_github("mac-theobio/McMasterPandemic@tmb-condense")'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Render Book
        run: Rscript -e 'rmarkdown::render_site(output_format = "bookdown::gitbook", encoding = "UTF-8")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main # The branch the action should deploy to.
          folder: _book # The folder the action should deploy.
          clean: false
          target-folder: docs
